name: image_crop_example
description: Demonstrates how to use the image_crop plugin.

version: 1.0.0+1

environment:
    sdk: ">=2.17.6 <4.0.0"
    flutter: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.5
    image_picker: ^1.1.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    simple_image_crop:
        path: ../

flutter:
    uses-material-design: true
