name: simple_image_crop_plus
description: A simple and easy to use flutter plugin to crop image on iOS and Android.
version: 1.0.3
homepage: https://github.com/MCYBA/flutter_simple_image_crop.git

environment:
    sdk: ">=2.17.6 <4.0.0"
    flutter: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    plugin:
        platforms:
            android:
                package: com.lykhonis.simpleimagecrop
                pluginClass: SimpleImageCropPlugin
            ios:
                pluginClass: SimpleImageCropPlugin
